### ISSUE TITLE
Android 4.1.1 Crash

### ISSUE THREAD

**Issue by joaortk** [keannan5390/Xamarin.Plugin.FAB#4]
Android app crashing with latest version (v2.1.1) on Android 4.1.1 Device.
Error message: Java.Lang.LinkageError: no method with name='setElevation' signature='(F)V' in class Landroid/view/View;

Project running with:
Xamarin Forms 2.3.0.107
Xamarin.Android.Support.v7.AppCompat 23.3.0

FAB Works fine with v2.1.0

**Comment by jaroslavrehorka** [comment]
+1

**Comment by jaroslavrehorka** [comment]
Problem is with https://github.com/keannan5390/Xamarin.Plugin.FAB/blob/master/Library/FloatingActionButton.Droid/FloatingActionButtonRenderer.cs#L125 SetHasShadow which is not available in pre-material API (http://stackoverflow.com/questions/35732177/android-app-crashing-java-lang-nosuchmethoderror)

**Comment by richardalmonte** [comment]
I'm having the same problem with android 4.4.4 and FAB.Forms 2.1.1.0

How can I solve it?

thanks!

**Comment by jaroslavrehorka** [comment]
Update to 2.1.2 should solve it, this issue was resolved in #5

**Comment by maxime-kouemo** [comment]
I have the same problem, I did the update and it solved nothing

**Comment by jjsan** [comment]
same problem here
why is it closed? problem is still here

**Comment by pgenfer** [comment]
I had the same issue, even after installing 2.1.2 prebuild. 
Updating my jdk version to jdk-8u121 (and pointing Xamarin installation to latest jdk) fixed it for me.

**Comment by parth7676** [comment]
@pgenfer I have installed 2.1.2 prebuild also updated jdk still getting the problem.

**Comment by dalyntechnologies** [comment]
prebuild 2.1.2 works fine only if you clean and rebuild solution,i did that and it worked.

**Comment by kvaldes01** [comment]
Me too, prebuild 2.1.2 --> clean and rebuild.

**Comment by oguzhanorhaan** [comment]
I had same problem, updating to prebuild 2.2.0 and clean rebuild solved my problem
